Update the GH summarization example to Kubeflow 0.2 and TFJob v1alpha2. (#157)
* Update the GH summarization example to Kubeflow 0.2 and TFJob v1alpha2.

* Upgrade the ksonnet app to Kubeflow 0.2 rc.1
* Add the examples package.
* Add a .gitignore file and ignore all environments so that we won't pick
  up people's testing environments.

* Add tfjob-v1alpha2 component; this trains the model using Keras using
  TFJob v1alpha2.
  * Update the parameters so that we use the GCP secrets created as part
    of the Kubeflow deployment.

* Remove jlewi environment.

* Verified that training ran successfully and outputted a model to GCS

  * There was an error about some missing arguments to a logging statement
    but this can be ignored although it would be good to fix.

* Started working on T2T v1alpha2. Seems to be messing up the app.

* Update the v1alpha2 template for the tensor2tensor job but it looks like
there is an error

2018-06-29 17:45:23,369] Found unknown flag: --problem=github_issue_summarization_problem
Traceback (most recent call last):
  File "/home/jovyan/.conda/bin/t2t-trainer", line 32, in <module>
    tf.app.run()
  File "/home/jovyan/.conda/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/home/jovyan/.conda/bin/t2t-trainer", line 28, in main
    t2t_trainer.main(argv)
  File "/home/jovyan/.conda/lib/python3.6/site-packages/tensor2tensor/bin/t2t_trainer.py", line 334, in main
    exp_fn = create_experiment_fn()
  File "/home/jovyan/.conda/lib/python3.6/site-packages/tensor2tensor/bin/t2t_trainer.py", line 158, in create_experiment_fn
    problem_name=get_problem_name(),
  File "/home/jovyan/.conda/lib/python3.6/site-packages/tensor2tensor/bin/t2t_trainer.py", line 115, in get_problem_name
    problems = FLAGS.problems.split("-")
AttributeError: 'NoneType' object has no attribute 'split'